### ISSUE TITLE
Search function ميزة البحث

### ISSUE THREAD

**Issue by Ehab-d** [Alsarmad/Altaqwaa-Islamic-Desktop-Application#30]
توفير مربع للبحث داخل مختلف الصفحات داخل التطبيق.

**Comment by Ehab-d** [comment]
@mohamedmhmed19 
> هل ممكن اقدر اعدل علي البرنامج
نعم تستطيع، فهو مفتوح المصدر بالكامل. الكود المصدري للبرنامج مُتاح في هذا المستودع على GitHub.
> 
> ماهي اللغات المستخدمه
تعتبر JavaScript هي الأساس في هذا المشروع؛ لإعتماد المطور على إطار العمل Electron.js.
----------
نصيحة لك صديقي الغالي، محمد:
قسم issues في GitHub مكانًا ليبلغ المستخدمين عن أخطاء في البرنامج، أو طلب ميزات جديدة.
بل وأنك تسأل السؤال في الـ issue الخاصة بي، والتي سياقها هو طلب ميزة معينة.
ليس من الإحترافي أن تسأل سؤالًا في هذا القسم. يُوفر المطور طرق مباشرة للإتصال به في README.

**Comment by m-1226** [comment]
السلام عليكم ورحمة الله وبركاته 
اخي الكريم 
الحمدلله قمت بإضافة ميزة مهم جدا بفضل الله 
ميزة البحث في القراء والسور 
ستيسر كثيرا علي المستخدم في البحث عن إسم أي قاري او أي سورة بمنتهي السهولة 
سأرفق لك فيديو يوضح كيف تعمل وأعمل حاليا علي إضافاتها في الأذكار بإذن الله 

https://github.com/Alsarmad/Altaqwaa-Islamic-Desktop-Application/assets/64734981/67c50f3e-6ab8-4b93-8443-5e2ab4aa8d87


وأعمل أيضا علي بعض المميزات الرائعة منها علي سبيل المثال ( تشغيل صوت ذكر واحد في الخلفية كل فترة يختارها المستخدم ) يعني مثلا (أستغفر الله العظيم تصدر ك صوت في الخلفية كل 20 دقيقة والذكر يتغير مرة الصلاة علي النبي مع التسبيح وهكذا بحيث يكون لسانه دائما عطر بذكر الله 
والكثير من المميزات أعمل عليها وبعون الله قريبا جدا سأنتهي منها وأرسل طلب الإضافة

**Comment by m-1226** [comment]
لا أعرف كيف أتواصل معك مباشرة ولكن 
هذا هو معرف التيليجرام الخاص بي 
أرسل رسالة فقط وبإذن الله راح يكون وسيلة التواصل بينا وإطلاعك علي كل ماهو جديد من المميزات اللي بفضل الله بقوم بإضافتها حتي تكون علي علم أول بأول ويكون كل شئ امامك عينك 
https://t.me/mahmoud_ashraf_yahia

**Comment by mohamedmhmed19** [comment]
تمام استأذن حضرتك ممكن اتشرف بالاسم

في الاثنين، ١٠ يوليو ٢٠٢٣ ٩:٢٨ ص MahmoudAshraf ***@***.***>
كتب:
